import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    ".eve/**",
    ".output/**",
    ".vercel/**",
    // Generated by the Workflow DevKit: the step/workflow bundles, its runtime data, and the
    // route handlers it writes under `src/app/.well-known/`.
    ".swc/**",
    ".workflow-data/**",
    ".workflow-vitest/**",
    "src/app/.well-known/**",
    "next-env.d.ts",
  ]),
]);
