import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";
import tseslint from "typescript-eslint";

// Architecture boundaries. The layers form a one-way dependency graph:
//   lib (leaf) ← domain ← persistence / workflows ← review-chat / app
// A layer may only import from itself and the layers below it. These zones
// stop an inversion (e.g. domain reaching into persistence) at lint time.
const restrictedImport = (message, patterns) => ({
  "no-restricted-imports": [
    "error",
    { patterns: patterns.map((group) => ({ group, message })) },
  ],
});

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    name: "naming-conventions",
    files: ["**/*.ts", "**/*.tsx", "**/*.mts"],
    plugins: { "ts-naming": tseslint.plugin },
    rules: {
      "ts-naming/naming-convention": [
        "error",
        { selector: "typeLike", format: ["PascalCase"] },
        {
          selector: "interface",
          format: ["PascalCase"],
          custom: { regex: "^I[A-Z]", match: false },
        },
        { selector: "enumMember", format: ["PascalCase"] },
      ],
    },
  },
  {
    name: "boundary-domain",
    files: ["src/domain/**"],
    rules: restrictedImport(
      "The domain layer is pure: it may only import from @/domain.",
      [
        [
          "@/app/**",
          "@/persistence/**",
          "@/workflows/**",
          "@/review-chat/**",
          "@/lib/**",
        ],
      ],
    ),
  },
  {
    name: "boundary-lib",
    files: ["src/lib/**"],
    rules: restrictedImport(
      "@/lib is a leaf utility layer and must not import other app layers.",
      [
        [
          "@/app/**",
          "@/domain/**",
          "@/persistence/**",
          "@/workflows/**",
          "@/review-chat/**",
        ],
      ],
    ),
  },
  {
    name: "boundary-persistence",
    files: ["src/persistence/**"],
    rules: restrictedImport(
      "@/persistence may depend on @/domain, not on app-level or workflow layers.",
      [["@/app/**", "@/workflows/**", "@/review-chat/**"]],
    ),
  },
  {
    name: "boundary-workflows",
    files: ["src/workflows/**"],
    rules: restrictedImport(
      "@/workflows may depend on @/domain and @/lib, not on persistence, app, or chat layers.",
      [["@/app/**", "@/persistence/**", "@/review-chat/**"]],
    ),
  },
  prettier,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    ".eve/**",
    ".output/**",
    ".vercel/**",
    // Generated by the Workflow DevKit: the step/workflow bundles, its runtime data, and the
    // route handlers it writes under `src/app/.well-known/`.
    ".swc/**",
    ".workflow-data/**",
    ".workflow-vitest/**",
    "src/app/.well-known/**",
    "next-env.d.ts",
  ]),
]);
